/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'severe' : IDL.Null,
  'moderate' : IDL.Null,
});
export const ReportStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'submitted' : IDL.Null,
  'underReview' : IDL.Null,
});
export const Time = IDL.Int;
export const HateCommentReport = IDL.Record({
  'status' : ReportStatus,
  'severityScore' : IDL.Nat,
  'reporterName' : IDL.Text,
  'flaggedCategories' : IDL.Vec(IDL.Text),
  'reporterEmail' : IDL.Text,
  'timestamp' : Time,
  'commentText' : IDL.Text,
  'riskLevel' : RiskLevel,
});

export const idlService = IDL.Service({
  'createReport' : IDL.Func(
      [IDL.Text, IDL.Nat, RiskLevel, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getReports' : IDL.Func([], [IDL.Vec(HateCommentReport)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'severe' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const ReportStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'submitted' : IDL.Null,
    'underReview' : IDL.Null,
  });
  const Time = IDL.Int;
  const HateCommentReport = IDL.Record({
    'status' : ReportStatus,
    'severityScore' : IDL.Nat,
    'reporterName' : IDL.Text,
    'flaggedCategories' : IDL.Vec(IDL.Text),
    'reporterEmail' : IDL.Text,
    'timestamp' : Time,
    'commentText' : IDL.Text,
    'riskLevel' : RiskLevel,
  });
  
  return IDL.Service({
    'createReport' : IDL.Func(
        [IDL.Text, IDL.Nat, RiskLevel, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getReports' : IDL.Func([], [IDL.Vec(HateCommentReport)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };