/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface HateCommentReport {
  'status' : ReportStatus,
  'severityScore' : bigint,
  'reporterName' : string,
  'flaggedCategories' : Array<string>,
  'reporterEmail' : string,
  'timestamp' : Time,
  'commentText' : string,
  'riskLevel' : RiskLevel,
}
export type ReportStatus = { 'resolved' : null } |
  { 'submitted' : null } |
  { 'underReview' : null };
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'severe' : null } |
  { 'moderate' : null };
export type Time = bigint;
export interface _SERVICE {
  'createReport' : ActorMethod<
    [string, bigint, RiskLevel, Array<string>, string, string],
    undefined
  >,
  'getReports' : ActorMethod<[], Array<HateCommentReport>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];