/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface HateCommentReport {
    status: ReportStatus;
    severityScore: bigint;
    reporterName: string;
    flaggedCategories: Array<string>;
    reporterEmail: string;
    timestamp: Time;
    commentText: string;
    riskLevel: RiskLevel;
}
export enum ReportStatus {
    resolved = "resolved",
    submitted = "submitted",
    underReview = "underReview"
}
export enum RiskLevel {
    low = "low",
    high = "high",
    severe = "severe",
    moderate = "moderate"
}
export interface backendInterface {
    createReport(commentText: string, severityScore: bigint, riskLevel: RiskLevel, flaggedCategories: Array<string>, reporterName: string, reporterEmail: string): Promise<void>;
    getReports(): Promise<Array<HateCommentReport>>;
}
import type { HateCommentReport as _HateCommentReport, ReportStatus as _ReportStatus, RiskLevel as _RiskLevel, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createReport(arg0: string, arg1: bigint, arg2: RiskLevel, arg3: Array<string>, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createReport(arg0, arg1, to_candid_RiskLevel_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReport(arg0, arg1, to_candid_RiskLevel_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
            return result;
        }
    }
    async getReports(): Promise<Array<HateCommentReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReports();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReports();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_HateCommentReport_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HateCommentReport): HateCommentReport {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ReportStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportStatus): ReportStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ReportStatus;
    severityScore: bigint;
    reporterName: string;
    flaggedCategories: Array<string>;
    reporterEmail: string;
    timestamp: _Time;
    commentText: string;
    riskLevel: _RiskLevel;
}): {
    status: ReportStatus;
    severityScore: bigint;
    reporterName: string;
    flaggedCategories: Array<string>;
    reporterEmail: string;
    timestamp: Time;
    commentText: string;
    riskLevel: RiskLevel;
} {
    return {
        status: from_candid_ReportStatus_n6(_uploadFile, _downloadFile, value.status),
        severityScore: value.severityScore,
        reporterName: value.reporterName,
        flaggedCategories: value.flaggedCategories,
        reporterEmail: value.reporterEmail,
        timestamp: value.timestamp,
        commentText: value.commentText,
        riskLevel: from_candid_RiskLevel_n8(_uploadFile, _downloadFile, value.riskLevel)
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    submitted: null;
} | {
    underReview: null;
}): ReportStatus {
    return "resolved" in value ? ReportStatus.resolved : "submitted" in value ? ReportStatus.submitted : "underReview" in value ? ReportStatus.underReview : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    severe: null;
} | {
    moderate: null;
}): RiskLevel {
    return "low" in value ? RiskLevel.low : "high" in value ? RiskLevel.high : "severe" in value ? RiskLevel.severe : "moderate" in value ? RiskLevel.moderate : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HateCommentReport>): Array<HateCommentReport> {
    return value.map((x)=>from_candid_HateCommentReport_n4(_uploadFile, _downloadFile, x));
}
function to_candid_RiskLevel_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): _RiskLevel {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): {
    low: null;
} | {
    high: null;
} | {
    severe: null;
} | {
    moderate: null;
} {
    return value == RiskLevel.low ? {
        low: null
    } : value == RiskLevel.high ? {
        high: null
    } : value == RiskLevel.severe ? {
        severe: null
    } : value == RiskLevel.moderate ? {
        moderate: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
